## Statistical Analysis of Study of Icy Moons Morphology and Topology using Saturn’s Moon Rhea

### Group Members: Chris Guo, Jacynda Alatoma, Zhizhong Guan, Nolan Maher

In [8]:
import numpy as np
import matplotlib.pyplot as plt
from astropy.io import fits
from astropy.io import ascii
from scipy.stats import norm
import pandas as pd
import scipy.stats as stats
import random
from scipy.stats import binom
from scipy.stats import beta
import matplotlib.pyplot as plt
import os

In [15]:
# Read in the data from laptop and modify to get rid of rows
data = pd.read_csv("simple_RheaData.csv")
data.drop(columns = ['Sadness', 'BigSad', 'Pain', 'What even'])

      Diameter     Depth       d/D        CWS
0     7.945807  0.574980  0.072694   6.356729
1     9.053693  0.495266  0.054509   6.914289
2    12.400679  1.235135  0.099064  11.408845
3     9.833648  1.296110  0.132319  14.553500
4    11.258459  0.818526  0.074080   8.325040
..         ...       ...       ...        ...
243   7.383411  1.070948  0.150956  17.393374
244   9.494697  1.155795  0.122409  13.775448
245   9.173613  1.467976  0.169577  19.429568
246   7.003554  1.006688  0.144069  12.307677
247  12.272766  1.033345  0.085211  10.744094

[248 rows x 4 columns]

## Components of the Statistical Model
1. We assume that the distribution of the diameter (in Km) is approximately distributed normal with $N(\theta, v)$ where $\theta$ is the unknown diameter of a crater and we need to make a decision for the variance. For the variance we will choose STILL NEED TO FIGURE THIS OUT.
2. Our $\Theta$, or parameter space is [0,$\infty$) (in Km)
3. Our observed data , or x is [4.293, 18.085]
4. Our sample space is [0, $\infty$)
5. The likelihood is $p(x|\theta)$ (page 30 in notes)
6. The prior is distributed as $\upsilon(\theta) \sim N(a,b)$ where a and b are hyperparamters chosen from prior knowledge.